### ISSUE TITLE
Organization Status Update Throws Error, no Logging

### ISSUE THREAD

**Issue by hcrites54** [OSCELOT/UoY-DSK-Tool#1]
Have duplicated issue on version 2.5.0 in 3500.11.0, on version 2.5.0 in 3600.0.0 (without OpenJDK) and on version 2.5.1 in 3600.0.0 (TechPreview original with OpenJDK).

When updating an organization using UofY DSK, the update occurs but the logging fails and screen confirmation displays an error. There may be an issue with entries going into the york_dsk_change_message.dsk_type field.

**Steps to Duplicate**
1. Access U of Y
2. Select Organisation > Organisation Search
3. Select "Organisation ID" and "Contains"
4. Enter a value for an organization (I entered "HCD-SAFETY-2016-ORG")
5. Click "Go"
6. Check appropriate organization
7. Check "Update the records selected above"
8. Check "Status"
9. Change "Enabled" to "Disabled"
10. Click "Submit"

**Expected Behavior**
1. Change in status is successful
2. Entries appear in york_dsk_change_log and york_dsk_change_message
3. Confirmation screen displays showing success/failure messages

**Observed Behavior**
1. Change in status IS successful and the organization IS now disabled
2. There are no entries for the operation in york_dsk_change_log and york_dsk_change_message
3. There are no confirmations or list of success/failure messages. Instead, an error is displayed:

Could not perform database operation. An unknown error has occurred. ERROR: value too long for type character varying(15)

The top few lines from Kibana are below:
2019-03-19 08:52:18 -0400 - [WARNING] Could not perform database operation. An unknown error has occurred. ERROR: value too long for type character varying(15)<P><span class="captionText">For reference, the Error ID is 32d0a711-ae81-47c1-a11f-5407e2d44c6b.</span> - org.postgresql.util.PSQLException: ERROR: value too long for type character varying(15) at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440) at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183) at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308) at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441) at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365) at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143) at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:120)

I can provide a download of the error log entry if that would be helpful.

**Comment by Kelvin-Hai** [comment]
A download to the full error log for the action would definitely be helpful. Please also include any log that contain uk.ac.york.its.vle.b2.dsk

**Comment by Kelvin-Hai** [comment]
FIxed in version 2.5.2
